<a href="https://colab.research.google.com/github/isathik/Day1-test/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Hello Dr. Sathik  Day1**

In [ ]:
import numpy as np
a =  [1,2,3,4]
arr1 = np.array(a)
print (arr1)
b=[[1,2,3,4], [2,2,3,4]]

arr2 = np.array(b)
print (arr2)

[1 2 3 4]
[[1 2 3 4]
 [2 2 3 4]]


In [ ]:
import time
a = range(1000)
b= range(1000)

start = time.time()
print (start)
ab =  [ (a * b) for  a,b in zip(a,b)]

end = time.time()
print (end - start)

1622099725.0012016
0.002811431884765625


In [ ]:
arr3= np.array([[1,2,3],[4,5,6]], ndmin=2)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
print (arr3.dtype)
print (arr3.ndim)
print (arr3.shape)
print (arr3.size)

int64
2
(2, 3)
6


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
a =  [1,2,3,4]
a[3]
a[-1]
a[-2]
a[0:4]
a[0]=8
print (a)
print (a[2:])
print(a[:3])





[8, 2, 3, 4]
[3, 4]
[8, 2, 3]


In [ ]:
import pandas as pd
dataset = pd.read_csv("/content/sample_data/california_housing_test.csv")
dataset.head(10)

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0
5    -119.56     36.51  ...         1.6635             67000.0
6    -121.43     38.63  ...         1.6641             67000.0
7    -120.65     35.48  ...         3.2250            166900.0
8    -122.84     38.40  ...         3.6696            194400.0
9    -118.02     34.08  ...         2.3333            164200.0

[10 rows x 9 columns]

In [ ]:
dataset.tail()

longitude  latitude  ...  median_income  median_house_value
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[5 rows x 9 columns]

In [ ]:
dataset.head()


longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0

[5 rows x 9 columns]

In [ ]:
dataset.shape

(3000, 9)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [ ]:
dataset.describe()

longitude    latitude  ...  median_income  median_house_value
count  3000.000000  3000.00000  ...    3000.000000          3000.00000
mean   -119.589200    35.63539  ...       3.807272        205846.27500
std       1.994936     2.12967  ...       1.854512        113119.68747
min    -124.180000    32.56000  ...       0.499900         22500.00000
25%    -121.810000    33.93000  ...       2.544000        121200.00000
50%    -118.485000    34.27000  ...       3.487150        177650.00000
75%    -118.020000    37.69000  ...       4.656475        263975.00000
max    -114.490000    41.92000  ...      15.000100        500001.00000

[8 rows x 9 columns]

In [ ]:
dataset2=pd.read_html("https://en.wikipedia.org/wiki/Machine_learning")
dataset2.head()


AttributeError: ignored