<a href="https://colab.research.google.com/github/isathik/Day1-test/blob/main/Day31_05_2021_Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## K-Fold cross validation

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv("/content/Social_Network_Ads.csv")
#identifying dependant and independant variable
x=dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [ ]:
dataset.shape


(400, 3)

In [ ]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[    53  34000]
 [    57  33000]
 [    37 137000]
 [    35  55000]
 [    46  82000]
 [    35  23000]
 [    24  55000]
 [    33  51000]
 [    48  29000]
 [    35  72000]
 [    32 117000]
 [    40 107000]
 [    35  39000]
 [    28  79000]
 [    27  54000]
 [    38  61000]
 [    35  77000]
 [    23  63000]
 [    32 117000]
 [    39  75000]
 [    42 104000]
 [    37 146000]
 [    28  59000]
 [    48  90000]
 [    39  59000]
 [    53 143000]
 [    39  77000]
 [    58  95000]
 [    36 144000]
 [    35  73000]
 [    28  85000]
 [    48 134000]
 [    32 150000]
 [    37  53000]
 [    26  84000]
 [    28  87000]
 [    39  71000]
 [    29  83000]
 [    40  75000]
 [    19  25000]
 [    25  87000]
 [    60 108000]
 [    45  79000]
 [    33 113000]
 [    35  50000]
 [    52 150000]
 [    50  88000]
 [    49  28000]
 [    52 138000]
 [    48  35000]
 [    49  74000]
 [    36  63000]
 [    28  84000]
 [    34  25000]
 [    55 130000]
 [    29  75000]
 [    47  20000]
 [    36  54000]
 [    33  4300

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

print (x_train)
print (x_test)


[[ 1.43536429e+00 -1.05268579e+00]
 [ 1.81872444e+00 -1.08193518e+00]
 [-9.80763049e-02  1.96000207e+00]
 [-2.89756380e-01 -4.38448456e-01]
 [ 7.64484032e-01  3.51285254e-01]
 [-2.89756380e-01 -1.37442915e+00]
 [-1.34399679e+00 -4.38448456e-01]
 [-4.81436454e-01 -5.55446043e-01]
 [ 9.56164106e-01 -1.19893277e+00]
 [-2.89756380e-01  5.87912873e-02]
 [-5.77276492e-01  1.37501414e+00]
 [ 1.89443807e-01  1.08252017e+00]
 [-2.89756380e-01 -9.06438803e-01]
 [-9.60636641e-01  2.63537064e-01]
 [-1.05647668e+00 -4.67697853e-01]
 [-2.23626754e-03 -2.62952076e-01]
 [-2.89756380e-01  2.05038271e-01]
 [-1.43983683e+00 -2.04453283e-01]
 [-5.77276492e-01  1.37501414e+00]
 [ 9.36037698e-02  1.46539477e-01]
 [ 3.81123882e-01  9.94771981e-01]
 [-9.80763049e-02  2.22324664e+00]
 [-9.60636641e-01 -3.21450870e-01]
 [ 9.56164106e-01  5.85280428e-01]
 [ 9.36037698e-02 -3.21450870e-01]
 [ 1.43536429e+00  2.13549845e+00]
 [ 9.36037698e-02  2.05038271e-01]
 [ 1.91456448e+00  7.31527411e-01]
 [-1.93916342e-01  2

In [ ]:
data = pd.read_csv("/content/Data.csv")
#identifying dependant and independant variable
x=data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [ ]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[1121919       5       1 ...       2       1       1]
 [1112209       8      10 ...       3       9       1]
 [1205579       8       7 ...       5       1       1]
 ...
 [1197080       4       1 ...       3       2       1]
 [ 878358       5       7 ...       7       5       1]
 [1116998      10       4 ...       4       3      10]]
[2 4 4 2 2 4 2 2 2 2 4 2 2 2 4 2 2 4 4 2 4 4 2 2 2 4 4 4 2 4 2 4 2 2 2 2 4
 2 4 4 2 2 2 4 2 2 2 4 2 4 2 2 2 4 2 4 4 4 2 2 2 2 2 2 2 2 4 4 2 4 2 2 2 4
 2 2 2 4 2 2 4 2 2 4 2 4 2 2 2 4 2 2 4 2 2 4 2 4 2 2 4 2 2 2 2 4 4 2 2 4 2
 2 2 4 4 2 2 2 2 2 2 4 4 2 2 4 2 4 4 2 2 4 2 2 2 4 2 2 2 2 2 2 2 4 4 2 2 4
 2 2 2 2 2 2 2 2 4 4 2 2 2 2 4 4 2 4 2 2 4 4 2 2 4 2 2 2 2 2 4 2 2 2 2 2 4
 2 2 2 2 4 2 4 4 2 4 2 4 4 2 4 4 2 2 2 4 2 2 4 2 4 2 4 2 4 4 4 2 4 2 4 2 2
 4 2 4 2 2 2 2 4 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2 2 2 4 2 2 4 4 2 4 2 4 4 4
 2 2 4 2 2 4 2 2 2 2 4 4 2 4 2 2 2 4 4 2 2 2 2 2 2 2 4 4 4 2 2 2 4 2 2 4 2
 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2 2 4 2 2 2 4 2 2 4 2 2 4 2 2 2 2

In [ ]:
#train the xgboost model
from xgboost import XGBClassifier
xgb =XGBClassifier()
xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:

y_pred = xgb.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
cm = confusion_matrix(y_pred,y_test)
print(cm)
accuracy_score(y_test,y_pred)

[[101   0]
 [  4  66]]


0.9766081871345029

In [ ]:
#Naive bayes Algo implementation
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [ ]:
from sklearn.model_selection import cross_val_score

accuracies = cross_val_score(estimator = xgb, X = x_train,  y = y_train, cv = 40)

print("Accuracy : {:.2f}%".format(accuracies.mean() * 100))
print("Standard Devaition: {:.2f}%".format(accuracies.std() * 100))

Accuracy : 96.67%
Standard Devaition: 5.28%
